---
all:
  children:
    monitoring:
      hosts:
        localhost:
          ansible_connection: local

    proxmox:
      hosts:
        45D-247Support1:
          ansible_host: 192.168.45.1
        45D-247Support2:
          ansible_host: 192.168.45.2
        45D-247Support3:
          ansible_host: 192.168.45.3